// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghurkzxarndwdvkckisc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdodXJrenhhcm5kd2R2a2NraXNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MzIzMjQsImV4cCI6MjA2NjMwODMyNH0.bs05_L71iW3uIfns6KOAcS7qfmggZa2vVF0xa1fyZpY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});